package sfc.engine

import sfc.accounting.{BankState, BopState, ForexState, GovState, MonetaryAggregates}
import sfc.agents.{BankingSectorState, DemographicsState, HhAggregates, HhState, Household, ImmigrationState, InsuranceSector, InsuranceSectorState, JstState, NbfiState, NbpState, PpkState, ShadowBanking, ZusState}
import sfc.engine.{EquityMarketState, HousingMarketState, SectoralMobilityState}
import sfc.types.*

case class World(
  month: Int,
  inflation: Double,
  priceLevel: Double,
  gov: GovState,
  nbp: NbpState,
  bank: BankState,
  forex: ForexState,
  hh: HhState,
  automationRatio: Double,
  hybridRatio: Double,
  gdpProxy: Double,
  currentSigmas: Vector[Double],
  ioFlows: PLN = PLN.Zero,
  bop: BopState = BopState.zero,
  hhAgg: Option[HhAggregates] = None,
  households: Option[Vector[Household]] = None,
  bankingSector: Option[BankingSectorState] = None,
  monetaryAgg: Option[MonetaryAggregates] = None,
  jst: JstState = JstState.zero,
  zus: ZusState = ZusState.zero,
  ppk: PpkState = PpkState.zero,
  demographics: DemographicsState = DemographicsState.zero,
  macropru: MacropruState = MacropruState.zero,
  equity: EquityMarketState = EquityMarket.zero,
  housing: HousingMarketState = HousingMarket.zero,
  sectoralMobility: SectoralMobilityState = SectoralMobility.zero,
  gvc: GvcState = ExternalSector.zero,
  expectations: ExpectationsState = Expectations.zero,
  immigration: ImmigrationState = ImmigrationState.zero,
  corporateBonds: CorporateBondMarketState = CorporateBondMarket.zero,
  insurance: InsuranceSectorState = InsuranceSector.zero,
  nbfi: NbfiState = ShadowBanking.zero,
  sectorDemandMult: Vector[Double] = Vector.fill(6)(1.0),
  fofResidual: Double = 0.0,
  grossInvestment: PLN = PLN.Zero,
  fdiProfitShifting: PLN = PLN.Zero,
  fdiRepatriation: PLN = PLN.Zero,
  fdiCitLoss: PLN = PLN.Zero,
  firmBirths: Int = 0,
  firmDeaths: Int = 0,
  aggInventoryStock: PLN = PLN.Zero,
  aggInventoryChange: PLN = PLN.Zero,
  informalCyclicalAdj: Double = 0.0,
  taxEvasionLoss: PLN = PLN.Zero,
  informalEmployed: PLN = PLN.Zero,
  aggEnergyCost: PLN = PLN.Zero,
  aggGreenCapital: PLN = PLN.Zero,
  aggGreenInvestment: PLN = PLN.Zero,
  diasporaRemittanceInflow: PLN = PLN.Zero,
  tourismExport: PLN = PLN.Zero,
  tourismImport: PLN = PLN.Zero,
  bfgFundBalance: PLN = PLN.Zero,
  bailInLoss: PLN = PLN.Zero
)
