package sfc.engine

import sfc.accounting.*
import sfc.agents.*
import sfc.types.*

case class World(
  month: Int,
  inflation: Rate,
  priceLevel: Double,
  gov: GovState,
  nbp: Nbp.State,
  bank: BankingAggregate,
  forex: ForexState,
  hh: Household.SectorState,
  automationRatio: Ratio,
  hybridRatio: Ratio,
  gdpProxy: Double,
  currentSigmas: Vector[Double],
  ioFlows: PLN = PLN.Zero,
  bop: BopState = BopState.zero,
  hhAgg: Option[Household.Aggregates] = None,
  households: Option[Vector[Household.State]] = None,
  bankingSector: Banking.State,
  monetaryAgg: Option[MonetaryAggregates] = None,
  jst: Jst.State = Jst.State.zero,
  zus: SocialSecurity.ZusState = SocialSecurity.ZusState.zero,
  ppk: SocialSecurity.PpkState = SocialSecurity.PpkState.zero,
  demographics: SocialSecurity.DemographicsState = SocialSecurity.DemographicsState.zero,
  macropru: Macroprudential.State = Macroprudential.State.zero,
  equity: EquityMarket.State = EquityMarket.zero,
  housing: HousingMarket.State = HousingMarket.zero,
  sectoralMobility: SectoralMobility.State = SectoralMobility.zero,
  gvc: GvcTrade.State = GvcTrade.zero,
  expectations: Expectations.State = Expectations.zero,
  immigration: Immigration.State = Immigration.State.zero,
  corporateBonds: CorporateBondMarket.State = CorporateBondMarket.zero,
  insurance: Insurance.State = Insurance.zero,
  nbfi: Nbfi.State = Nbfi.zero,
  sectorDemandMult: Vector[Double] = Vector.fill(6)(1.0),
  fofResidual: Double = 0.0,
  grossInvestment: PLN = PLN.Zero,
  fdiProfitShifting: PLN = PLN.Zero,
  fdiRepatriation: PLN = PLN.Zero,
  fdiCitLoss: PLN = PLN.Zero,
  firmBirths: Int = 0,
  firmDeaths: Int = 0,
  aggInventoryStock: PLN = PLN.Zero,
  aggInventoryChange: PLN = PLN.Zero,
  informalCyclicalAdj: Double = 0.0,
  taxEvasionLoss: PLN = PLN.Zero,
  informalEmployed: PLN = PLN.Zero,
  aggEnergyCost: PLN = PLN.Zero,
  aggGreenCapital: PLN = PLN.Zero,
  aggGreenInvestment: PLN = PLN.Zero,
  diasporaRemittanceInflow: PLN = PLN.Zero,
  tourismExport: PLN = PLN.Zero,
  tourismImport: PLN = PLN.Zero,
  bfgFundBalance: PLN = PLN.Zero,
  bailInLoss: PLN = PLN.Zero,
)
